{% set version = "0.9.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-modelbased
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/modelbased_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/modelbased/modelbased_{{ version }}.tar.gz
  sha256: 8b7ae898c832b481b2acc141d7d6b12e53e46aae665a365517307e6a8b39db26

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-bayestestr >=0.12.1
    - r-datawizard >=0.5.0
    - r-effectsize >=0.7.0
    - r-insight >=0.18.0
    - r-parameters >=0.18.0
    - r-performance >=0.9.0
  run:
    - r-base
    - r-bayestestr >=0.12.1
    - r-datawizard >=0.5.0
    - r-effectsize >=0.7.0
    - r-insight >=0.18.0
    - r-parameters >=0.18.0
    - r-performance >=0.9.0

test:
  commands:
    - $R -e "library('modelbased')"           # [not win]
    - "\"%R%\" -e \"library('modelbased')\""  # [win]

about:
  home: https://easystats.github.io/modelbased/
  license: GPL-3.0-only
  summary: Implements a general interface for model-based estimations for a wide variety of models (see list of supported models using the function 'insight::supported_models()'), used in the computation of marginal means, contrast analysis and predictions.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
